# Retrieving meaningful dimensions using AABCC score

## 1. Description  
In this Notebook, we will implement and use a new metric to measure the meaningfulness of a WE dimension for a classification task.

In [1]:
import pandas as pd
df_n = pd.read_csv("../Data/all_nouns_we.csv")
df_n["gender"] = df_n["gender"].apply(lambda x:"F" if x=="feminine" else "M") 
df_n.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,504,505,506,507,508,509,510,511,gn,gender
0,abaisse,4.652041,-4.028067,0.883202,4.782082,-2.294611,-3.894453,-0.810279,-0.713933,4.819906,...,-1.768522,0.557448,-1.204734,-5.865204,-7.542219,-4.662949,-0.546076,-1.836027,singular,F
1,abandonnée,3.936752,1.365095,0.601899,-3.841945,0.137241,-6.720108,-4.014627,-0.164519,-4.163124,...,-1.122231,-4.691674,-1.861967,-7.399371,-3.871466,-4.995701,4.840463,-0.697731,singular,F
2,abattue,5.501807,0.974496,1.963397,-0.096684,-0.317693,-5.214660,-1.325345,1.782016,2.419068,...,-1.418699,-2.060775,-4.221079,-9.340311,-6.799405,-3.366512,-1.183914,-0.273903,singular,F
3,abbaye,4.343249,-4.697087,1.981792,0.167565,4.937754,-5.705141,-4.314447,-2.714383,-1.888555,...,4.184031,3.421206,-1.783199,-6.933277,-5.636909,3.233929,-3.364212,-5.757182,singular,F
4,abdominale,4.454150,-0.297545,4.704999,0.880275,0.379564,-3.872901,-2.538447,-7.180586,10.115621,...,-0.737049,-1.824200,-0.034769,-2.647907,-4.493944,-0.005413,4.762722,-5.029149,singular,F

In [2]:
df_n.sort_values("0")[["0", "gender"]]

               0 gender
2522   -7.234042      F
12489  -6.904568      M
11048  -6.609836      M
5652   -6.572830      F
4652   -6.460532      F
...          ...    ...
1571   12.605267      F
1598   12.682314      F
11169  13.303518      M
2926   13.810582      F
3858   13.867551      F

[13238 rows x 2 columns]

In [55]:
def get_sequence(df:pd.DataFrame, dim:int, feature:str):
    return list(df.sort_values(str(dim))[feature])

def get_score_for_sequence(seq:list):
    
    # initialisation
    score = 0
    i = 0 # current index
    val = seq[0] # current value

    while i < len(seq):
        j = 0 # consecutive values counter

        while i < len(seq) and seq[i] == val:
            j += 1
            i += 1
        
        score += sum([i for i in range(j+1)])
        
        if i < len(seq):
             val = seq[i]

    return score

In [56]:
seq = list("aabbbabab")
get_score_for_sequence(seq)

13

In [57]:
d = {}
for i in range(512):
    seq = get_sequence(df_n, i, "gender")
    d[i] = get_score_for_sequence(seq)

In [58]:
sorted(d.items(), key = lambda x:x[1], reverse=True) # sorting the dimensions by score

[(100, 29081),
 (192, 28850),
 (403, 28665),
 (245, 28646),
 (377, 28625),
 (316, 28456),
 (195, 28382),
 (121, 28331),
 (507, 28139),
 (202, 28125),
 (117, 28112),
 (28, 28084),
 (74, 27987),
 (239, 27978),
 (310, 27942),
 (470, 27937),
 (362, 27926),
 (318, 27855),
 (274, 27842),
 (434, 27823),
 (477, 27804),
 (472, 27802),
 (443, 27769),
 (40, 27749),
 (306, 27732),
 (487, 27701),
 (237, 27683),
 (461, 27656),
 (256, 27655),
 (59, 27642),
 (389, 27632),
 (193, 27565),
 (326, 27558),
 (188, 27539),
 (455, 27523),
 (421, 27522),
 (439, 27521),
 (510, 27515),
 (55, 27503),
 (198, 27494),
 (296, 27490),
 (20, 27474),
 (474, 27459),
 (508, 27458),
 (207, 27455),
 (292, 27454),
 (41, 27438),
 (49, 27430),
 (321, 27426),
 (29, 27425),
 (119, 27423),
 (215, 27417),
 (174, 27414),
 (21, 27412),
 (179, 27410),
 (250, 27409),
 (374, 27395),
 (162, 27392),
 (176, 27392),
 (312, 27390),
 (276, 27387),
 (144, 27381),
 (51, 27379),
 (268, 27351),
 (6, 27348),
 (39, 27347),
 (432, 27336),
 (7, 27326),
 (90, 27325),
 (147, 27325),
 (366, 27319),
 (320, 27310),
 (151, 27309),
 (356, 27306),
 (113, 27303),
 (52, 27300),
 (413, 27299),
 (490, 27283),
 (383, 27274),
 (372, 27268),
 (267, 27264),
 (262, 27260),
 (187, 27259),
 (293, 27253),
 (368, 27247),
 (488, 27246),
 (225, 27242),
 (73, 27241),
 (300, 27241),
 (492, 27240),
 (499, 27237),
 (387, 27222),
 (363, 27212),
 (465, 27211),
 (307, 27204),
 (408, 27202),
 (433, 27200),
 (136, 27198),
 (69, 27195),
 (115, 27184),
 (390, 27181),
 (482, 27181),
 (506, 27179),
 (438, 27173),
 (399, 27168),
 (485, 27168),
 (230, 27162),
 (333, 27162),
 (76, 27161),
 (61, 27159),
 (189, 27150),
 (124, 27139),
 (152, 27138),
 (313, 27137),
 (269, 27135),
 (446, 27130),
 (87, 27125),
 (8, 27124),
 (286, 27121),
 (142, 27119),
 (160, 27119),
 (5, 27118),
 (31, 27116),
 (357, 27114),
 (279, 27113),
 (284, 27100),
 (417, 27100),
 (130, 27094),
 (205, 27093),
 (376, 27093),
 (254, 27092),
 (34, 27090),
 (128, 27085),
 (216, 27071),
 (486, 27071),
 (11, 27068),
 (141, 27067),
 (426, 27065),
 (181, 27063),
 (249, 27056),
 (88, 27055),
 (111, 27055),
 (234, 27055),
 (145, 27052),
 (199, 27050),
 (261, 27042),
 (54, 27041),
 (182, 27037),
 (407, 27037),
 (213, 27036),
 (331, 27036),
 (94, 27031),
 (14, 27029),
 (1, 27027),
 (429, 27027),
 (208, 27026),
 (248, 27026),
 (371, 27024),
 (244, 27023),
 (102, 27021),
 (260, 27021),
 (308, 27020),
 (2, 27018),
 (503, 27014),
 (212, 27013),
 (471, 27001),
 (419, 27000),
 (466, 26999),
 (140, 26997),
 (283, 26995),
 (505, 26993),
 (332, 26992),
 (431, 26992),
 (405, 26991),
 (336, 26986),
 (375, 26983),
 (64, 26981),
 (280, 26981),
 (409, 26980),
 (10, 26972),
 (63, 26970),
 (191, 26962),
 (340, 26961),
 (369, 26960),
 (67, 26959),
 (167, 26959),
 (25, 26958),
 (71, 26958),
 (464, 26958),
 (379, 26955),
 (157, 26954),
 (398, 26949),
 (448, 26946),
 (334, 26945),
 (273, 26943),
 (27, 26934),
 (491, 26934),
 (436, 26928),
 (500, 26928),
 (95, 26927),
 (26, 26925),
 (133, 26925),
 (289, 26918),
 (45, 26916),
 (105, 26916),
 (138, 26916),
 (184, 26910),
 (351, 26909),
 (58, 26907),
 (171, 26906),
 (123, 26897),
 (497, 26897),
 (424, 26894),
 (294, 26893),
 (135, 26889),
 (452, 26888),
 (92, 26882),
 (338, 26882),
 (150, 26881),
 (348, 26880),
 (30, 26879),
 (32, 26875),
 (247, 26875),
 (223, 26871),
 (46, 26867),
 (364, 26867),
 (502, 26866),
 (210, 26862),
 (47, 26857),
 (385, 26857),
 (4, 26854),
 (89, 26854),
 (137, 26854),
 (155, 26852),
 (218, 26849),
 (381, 26848),
 (509, 26848),
 (309, 26847),
 (412, 26845),
 (81, 26842),
 (97, 26840),
 (12, 26838),
 (35, 26838),
 (352, 26836),
 (220, 26834),
 (496, 26834),
 (272, 26827),
 (75, 26824),
 (108, 26823),
 (60, 26822),
 (175, 26819),
 (204, 26817),
 (120, 26816),
 (406, 26815),
 (479, 26813),
 (325, 26811),
 (190, 26809),
 (110, 26802),
 (341, 26799),
 (449, 26798),
 (257, 26797),
 (480, 26796),
 (404, 26793),
 (240, 26792),
 (288, 26791),
 (56, 26786),
 (411, 26786),
 (251, 26782),
 (227, 26780),
 (344, 26779),
 (139, 26778),
 (475, 26774),
 (422, 26771),
 (3, 26769),
 (106, 26765),
 (170, 26765),
 (122, 26764),
 (384, 26764),
 (232, 26762),
 (370, 26762),
 (361, 26761),
 (65, 26759),
 (493, 26759),
 (125, 26757),
 (456, 26756),
 (214, 26748),
 (82, 26745),
 (427, 26744),
 (388, 26739),
 (420, 26739),
 (402, 26735),
 (209, 26734),
 (50, 26733),
 (62, 26733),
 (504, 26720),
 (68, 26718),
 (37, 26717),
 (18, 26715),
 (287, 26715),
 (416, 26713),
 (104, 26709),
 (489, 26709),
 (186, 26708),
 (302, 26708),
 (484, 26707),
 (462, 26706),
 (178, 26705),
 (154, 26704),
 (222, 26703),
 (345, 26702),
 (481, 26702),
 (211, 26700),
 (15, 26699),
 (91, 26699),
 (172, 26699),
 (168, 26697),
 (291, 26697),
 (354, 26697),
 (468, 26696),
 (400, 26692),
 (457, 26691),
 (236, 26688),
 (454, 26688),
 (103, 26686),
 (270, 26686),
 (476, 26686),
 (277, 26684),
 (24, 26683),
 (70, 26683),
 (238, 26682),
 (317, 26682),
 (393, 26681),
 (435, 26679),
 (177, 26678),
 (17, 26676),
 (365, 26676),
 (127, 26675),
 (219, 26675),
 (373, 26674),
 (391, 26670),
 (281, 26667),
 (80, 26661),
 (200, 26660),
 (425, 26659),
 (57, 26656),
 (197, 26647),
 (342, 26647),
 (423, 26647),
 (43, 26637),
 (23, 26631),
 (83, 26630),
 (304, 26622),
 (305, 26620),
 (246, 26618),
 (126, 26615),
 (394, 26615),
 (9, 26613),
 (231, 26611),
 (107, 26609),
 (378, 26606),
 (346, 26603),
 (380, 26598),
 (243, 26596),
 (347, 26595),
 (159, 26590),
 (460, 26589),
 (173, 26586),
 (450, 26584),
 (451, 26584),
 (228, 26580),
 (445, 26578),
 (93, 26577),
 (33, 26576),
 (116, 26576),
 (319, 26575),
 (473, 26575),
 (16, 26574),
 (183, 26569),
 (196, 26569),
 (201, 26568),
 (358, 26567),
 (467, 26567),
 (396, 26564),
 (66, 26563),
 (180, 26560),
 (264, 26557),
 (303, 26557),
 (328, 26553),
 (146, 26550),
 (229, 26546),
 (350, 26545),
 (217, 26543),
 (314, 26541),
 (278, 26540),
 (266, 26539),
 (233, 26537),
 (430, 26536),
 (242, 26532),
 (271, 26529),
 (343, 26522),
 (79, 26519),
 (153, 26517),
 (258, 26516),
 (478, 26515),
 (323, 26511),
 (353, 26511),
 (38, 26510),
 (206, 26508),
 (275, 26508),
 (22, 26500),
 (221, 26499),
 (282, 26496),
 (322, 26494),
 (329, 26494),
 (98, 26491),
 (428, 26491),
 (169, 26488),
 (418, 26488),
 (85, 26486),
 (367, 26485),
 (392, 26483),
 (101, 26479),
 (495, 26474),
 (265, 26473),
 (118, 26472),
 (298, 26472),
 (36, 26471),
 (241, 26471),
 (444, 26471),
 (386, 26465),
 (78, 26462),
 (315, 26462),
 (494, 26456),
 (203, 26455),
 (339, 26454),
 (255, 26452),
 (259, 26451),
 (297, 26448),
 (156, 26445),
 (84, 26436),
 (99, 26433),
 (360, 26425),
 (224, 26421),
 (53, 26420),
 (129, 26415),
 (165, 26411),
 (42, 26407),
 (285, 26407),
 (359, 26406),
 (72, 26385),
 (415, 26385),
 (437, 26383),
 (0, 26379),
 (164, 26374),
 (410, 26373),
 (263, 26367),
 (355, 26366),
 (501, 26361),
 (13, 26358),
 (447, 26358),
 (337, 26348),
 (458, 26348),
 (77, 26343),
 (143, 26337),
 (395, 26333),
 (442, 26322),
 (327, 26321),
 (161, 26313),
 (301, 26312),
 (483, 26311),
 (299, 26309),
 (134, 26292),
 (194, 26285),
 (324, 26284),
 (469, 26280),
 (114, 26273),
 (86, 26272),
 (401, 26271),
 (96, 26266),
 (48, 26264),
 (148, 26262),
 (112, 26256),
 (235, 26249),
 (158, 26244),
 (441, 26242),
 (185, 26235),
 (498, 26231),
 (335, 26224),
 (163, 26215),
 (349, 26215),
 (440, 26211),
 (414, 26210),
 (311, 26209),
 (226, 26208),
 (382, 26195),
 (19, 26179),
 (290, 26173),
 (453, 26171),
 (132, 26169),
 (295, 26162),
 (459, 26151),
 (166, 26140),
 (330, 26121),
 (397, 26115),
 (253, 26108),
 (44, 26090),
 (109, 26060),
 (511, 26002),
 (131, 25969),
 (252, 25962),
 (149, 25826),
 (463, 25807)]